# Generated by Django 4.1.5 on 2023-03-22 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='artist',
        ),
    ]
