# Generated by Django 4.1.5 on 2023-01-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='song',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
