# Generated by Django 4.1.5 on 2023-03-22 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_line_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='line',
            name='album',
        ),
        migrations.RemoveField(
            model_name='line',
            name='song',
        ),
        migrations.RemoveField(
            model_name='line',
            name='year',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.DeleteModel(
            name='Instrument',
        ),
    ]
