# Generated by Django 4.1.5 on 2023-04-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_artist_instrument_remove_line_album_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='to_review',
            field=models.BooleanField(default=True),
        ),
    ]
