# Generated by Django 4.1.5 on 2023-04-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_line_to_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='line',
            old_name='key',
            new_name='original_key',
        ),
        migrations.AddField(
            model_name='line',
            name='original_line',
            field=models.TextField(default='TODO'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='progression',
            name='chords',
            field=models.TextField(default='TODO'),
            preserve_default=False,
        ),
    ]
