# Generated by Django 4.1.5 on 2023-04-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_key_line_original_key_line_original_line_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progression',
            name='mode',
            field=models.CharField(choices=[('Major', 'Major'), ('Minor', 'Minor')], default='Major', max_length=16),
            preserve_default=False,
        ),
    ]
