# Generated by Django 4.1.5 on 2023-04-15 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_progression_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='chords',
        ),
    ]
